### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Zhendong404** [KhronosGroup/OpenCL-ICD-Loader#10]
When I run "make" on Linux, it failed and output some errors like this, how can I fix it?

> In file included from /home/zhendong404/git/OpenCL-ICD-Loader/icd.c:39:0:
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1239:37: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      cl_command_queue command_queue) CL_API_SUFFIX__VERSION_2_1;
>                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1245:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      cl_int * errcode_ret) CL_API_SUFFIX__VERSION_2_1;
>                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1255:36: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      size_t * param_value_size_ret) CL_API_SUFFIX__VERSION_2_1;
>                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1259:27: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      cl_int * errcode_ret) CL_API_SUFFIX__VERSION_2_1;
>                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1269:23: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      cl_event * event) CL_API_SUFFIX__VERSION_2_1;
>                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1274:32: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      cl_ulong * host_timestamp) CL_API_SUFFIX__VERSION_2_1;
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1278:32: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_1’
>      cl_ulong * host_timestamp) CL_API_SUFFIX__VERSION_2_1;
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1455:5: error: unknown type name ‘KHRpfn_clCloneKernel’
>      KHRpfn_clCloneKernel                            clCloneKernel;
>      ^~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1456:5: error: unknown type name ‘KHRpfn_clCreateProgramWithIL’
>      KHRpfn_clCreateProgramWithIL                    clCreateProgramWithIL;
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1457:5: error: unknown type name ‘KHRpfn_clEnqueueSVMMigrateMem’
>      KHRpfn_clEnqueueSVMMigrateMem                   clEnqueueSVMMigrateMem;
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1458:5: error: unknown type name ‘KHRpfn_clGetDeviceAndHostTimer’
>      KHRpfn_clGetDeviceAndHostTimer                  clGetDeviceAndHostTimer;
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1459:5: error: unknown type name ‘KHRpfn_clGetHostTimer’
>      KHRpfn_clGetHostTimer                           clGetHostTimer;
>      ^~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1460:5: error: unknown type name ‘KHRpfn_clGetKernelSubGroupInfo’
>      KHRpfn_clGetKernelSubGroupInfo                  clGetKernelSubGroupInfo;
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/zhendong404/git/OpenCL-ICD-Loader/icd_dispatch.h:1461:5: error: unknown type name ‘KHRpfn_clSetDefaultDeviceCommandQueue’
>      KHRpfn_clSetDefaultDeviceCommandQueue           clSetDefaultDeviceCommandQueue;
>      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by reger-men** [comment]
Hey,
how did you  solve this issue?

**Comment by Zhendong404** [comment]
I didn't solve it, but I found ocl-icd works for me.
https://forge.imag.fr/projects/ocl-icd/

**Comment by flaub** [comment]
I'm having the same problem

**Comment by flaub** [comment]
I resolved this. In case it's not clear for anyone else, the headers need to match whatever the latest API version of this library is (2.2 at the time of this writing). So I did:
```
git clone https://github.com/KhronosGroup/OpenCL-Headers.git
cd inc
ln -s ../OpenCL-Headers/opencl22/CL/
cd ..
make
```

**Comment by markoshorro** [comment]
As a matter of a fact, this solution is still working; reason is the same as @flaub points
