### ISSUE TITLE
Can't load layers in CI

### ISSUE THREAD

**Issue by MathiasMagnus** [KhronosGroup/OpenCL-ICD-Loader#162]
What was the rationale of introducing the [secure_getenv](https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/88) handling "as per OpenCL WG discussion"? The problem is that we cannot test in CI on Windows because of this.

The default user in the image is ContainerAdministrator, which has high integrity level, and therefor we cannot load layers which are only available via environmental variables. I tried:

- lowering the integrity level via PsExec and runas /trustlevel:0x2000 but these commands don't work in docker containers. (limitation noted [here](https://serverfault.com/questions/357549/start-exe-in-a-remote-session-with-psexec))
- changing the user by starting a separate process as ContainerUser or Guest, but once again these commands fail silently and weirdly
- running the entire pipeline as regular user by instructing docker to use a non-default ([Obligatory SO](https://stackoverflow.com/a/58956931/1476661)) user and not installing the ICD but feeding it via OCL_ICD_FILENAMES . Feeding options to the docker command however is only supported for Linux containers.
![kép](https://user-images.githubusercontent.com/9763499/148964267-c26e63a4-49eb-4471-8722-872233c1d154.png)

One possible long term solution could be allowing to load layers programmatically like Vulkan does using [vkInstanceCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#VkInstanceCreateInfo), but I would like to find a solution for the short-mid term but I'm out of ideas.

**Comment by Kerilk** [comment]
As pointed out by @bashbaug would https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/154 help? If it could then I should be able to add you as a reviewer of the PR.

**Comment by MathiasMagnus** [comment]
@Kerilk Please do.

**Comment by Kerilk** [comment]
Closing as https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/154 has been merged and solves this issue.
