### ISSUE TITLE
Add CMake option to control tracing mode

### ISSUE THREAD

**Issue by MathiasMagnus** [KhronosGroup/OpenCL-ICD-Loader#165]
It's fairly cumbersome currently to debug ICD Loader issues in CI and Windows containers (tooling around handling Windows containers is subpar). If one wishes to debug things inside the loader, currently we need regex slice'n'dice in the source tree to enable tracing. A CMake option would improve the "expereince". (If that's the right word for debugging CI. :))

**Comment by bashbaug** [comment]
Do we want this to be a CMake option (and hence require a rebuild), or do you think it makes sense to have tracing compiled in by default and controlled by e.g. an environment variable?

We discussed this briefly in a previous "environment variable" issue (https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/48), but I don't think anyone has started on the tracing output part of this (yet).

**Comment by MathiasMagnus** [comment]
An env var would be better indeed.

**Comment by MathiasMagnus** [comment]
Closing this issue, as the [very same solution](https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/167) was brought up as an issue by independent developer.
