### ISSUE TITLE
Enable the internal trace in ICD loader

### ISSUE THREAD

**Issue by cdai2** [KhronosGroup/OpenCL-ICD-Loader#167]
Some times the OpenCL ICDs are not loaded successfully because of some reason.  But the user can not know the reason quickly. It's better that OpenCL ICD loader can provide some trance information or trace information.

Currently there is "KHR_ICD_TRACE" to provides some trance info but it's not enabled by default.  It's commented out by "#if 0" in icd.h fie.  I propose to use one environment variable to enable this "KHR_ICD_TRACE" macro so that user can get trace information.

**Comment by Kerilk** [comment]
This is a common suggestion, thanks for putting it back to the top of the list, and I think it is reasonable. Before we start we need to decide:
 - Name of the environment variable
 - Stream to use (configurable?)
 - Should we provide a registry key providing the same functionality as environment variables cannot be used on Windows while running securely
Are there other constraints/features I am overlooking?

**Comment by cdai2** [comment]
Thanks for feedback. Currently I have a draft patch.  I will submit for review soon:

- Name of the environment variable
      I used "OCL_ICD_ENABLE_TRACE" as environment variable following the pattern of existing ICD environment variables.

- Stream to use (configurable?)
      I use  "stderr".  We can add configurable stream.

- Should we provide a registry key providing the same functionality as environment variables cannot be used on Windows while running securely
     Personally I think the trace information is not secure.  The environment variable should be accessible under securely execution environment.  We do not need to provide registry key for to provide same functionality as environment variable.

**Comment by cdai2** [comment]
Please review https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/168.

**Comment by bashbaug** [comment]
I think this is fixed now, by #168?  Closing, but please feel free to reopen if there is still work to do, thanks!
