### ISSUE TITLE
difficulties building with 32-bit mingw-i686

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-ICD-Loader#191]
I've been trying to get the OpenCL ICD loader building and working properly with 32-bit mingw-i686 as part of https://github.com/KhronosGroup/OpenCL-SDK/issues/58 but I seem to have hit a bit of a dead end, so I'm at least documenting what I've tried in case it is helpful.

I'm cross-compiling on a Linux host (Ubuntu 20.04).  I have the mingw-w64 packages installed.

```sh
$ i686-w64-mingw32-g++ --version
i686-w64-mingw32-g++ (GCC) 9.3-posix 20200320
```

I'm trying to build my [SimpleOpenCLSamples](https://github.com/bashbaug/SimpleOpenCLSamples), which builds with the upstream OpenCL-Headers and OpenCL-ICD-Loader.  The specific commits I am using are:

* SimpleOpenCLSamples - https://github.com/bashbaug/SimpleOpenCLSamples/commit/42ca56455295414bb926f8aec9a2d32a8fe0af4f (latest in the main branch)
* OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/commit/b590a6bfe034ea3a418b7b523e3490956bcb367a (latest in the main branch)
* OpenCL-ICD-Loader - https://github.com/bashbaug/OpenCL-ICD-Loader/commit/6c51a7912d2a57754f6e8bf1bb4159458768f2a1 (latest in a branch with a few mingw fixes/improvements)

With these commits I am able to build an OpenCL.dll and a libOpenCL.dll.a import library, but I get an error when I link even the simplest sample with these libraries:

```sh
$ make clean enumopencl
[  8%] Building C object external/opencl-icd-loader/CMakeFiles/OpenCL.dir/loader/icd.c.obj
...
[ 83%] Linking C shared library OpenCL.dll
[ 83%] Built target OpenCL
[ 91%] Building CXX object samples/00_enumopencl/CMakeFiles/enumopencl.dir/main.cpp.obj
[100%] Linking CXX executable enumopencl.exe
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x148): undefined reference to `clGetPlatformInfo@20'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x1ad): undefined reference to `clGetPlatformInfo@20'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x350): undefined reference to `clGetDeviceInfo@20'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x3b5): undefined reference to `clGetDeviceInfo@20'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x5d2): undefined reference to `clGetDeviceInfo@20'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x9af): undefined reference to `clGetPlatformIDs@12'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0xa17): undefined reference to `clGetPlatformIDs@12'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0xab2): undefined reference to `clGetDeviceIDs@24'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/enumopencl.dir/objects.a(main.cpp.obj):main.cpp:(.text+0xb3e): undefined reference to `clGetDeviceIDs@24'
collect2: error: ld returned 1 exit status
make[3]: *** [samples/00_enumopencl/CMakeFiles/enumopencl.dir/build.make:101: samples/00_enumopencl/enumopencl.exe] Error 1
make[2]: *** [CMakeFiles/Makefile2:1326: samples/00_enumopencl/CMakeFiles/enumopencl.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1333: samples/00_enumopencl/CMakeFiles/enumopencl.dir/rule] Error 2
make: *** [Makefile:374: enumopencl] Error 2
```

The problem appears to be due to usage of the `stdcall` calling convention for 32-bit Windows, though I'm not 100% sure where things are going wrong.  Here is my current understanding:

1. The application itself is looking for a decorated function name (with the `@n` suffix for stdcall) and is not finding it, hence the linker failure.

2. The import library libOpenCL.dll.a does NOT decorate the functions it exports:

```sh
$ winedump -j export external/opencl-icd-loader/libOpenCL.dll.a 
Contents of external/opencl-icd-loader/libOpenCL.dll.a: 81250 bytes

248 public symbols
    1bd4 _OpenCL_dll_iname
    1d0e __head_OpenCL_dll
    1e8a _clWaitForEvents
    1e8a __imp__clWaitForEvents
    20d2 _clUnloadPlatformCompiler
    20d2 __imp__clUnloadPlatformCompiler
...
```

3. The DLL itself also does NOT decorate the functions it exports:

```sh
$ winedump -j export external/opencl-icd-loader/OpenCL.dll 
Contents of external/opencl-icd-loader/OpenCL.dll: 419689 bytes

Exports table:

  Name:            OpenCL.dll
  Characteristics: 00000000
  TimeDateStamp:   6344ADAB Mon Oct 10 16:41:31 2022
  Version:         0.00
  Ordinal base:    1
  # of functions:  123
  # of Names:      123
Addresses of functions: 00015028
Addresses of name ordinals: 00015400
Addresses of names: 00015214

  Entry Pt  Ordn  Name
  00003EE2     1 clBuildProgram
  000085AC     2 clCloneKernel
  00006ED5     3 clCompileProgram
...
```

(2) and (3) seem to be consistent with the OpenCL.def in this repo, which also does not decorate the functions it exports:

```
$ more ../external/opencl-icd-loader/loader/windows/OpenCL.def 
; copyright text removed here

EXPORTS

; comment removed here

; OpenCL 1.0 API
clBuildProgram
clCreateBuffer
clCreateCommandQueue
clCreateContext
...
```

I suppose this could still be the problem though?

Some things I tried:

* Adding the linker option `--add-stdcall-alias` (didn't seem to have an effect).
* Adding the linker option `--disable-stdcall-fixup` (couldn't link OpenCL.dll).
* Various combinations with the linker option `--kill-at` (didn't seem to have an affect).
* Changing OpenCL.def to explicitly add an alias to the decorated function (didn't seem to have an affect):

    ```
    clGetPlatformIDs = clGetPlatformIDs@12
    ```

* Changing OpenCL.def to only include the decorated function:

    ```
    clGetPlatformIDs@12
    ```

    I was able to link an executable with this change.  Not sure how viable of a solution this is, though...

**Comment by bashbaug** [comment]
A bit more information - this is on a native Windows system with an OpenCL.lib and OpenCL.dll built using MSVC 2019:

1. The import library OpenCL.lib DOES decorate the functions it exports.  This is true both for RelWithDebInfo and Release builds:

```cmd
>dumpbin /exports external\OpenCL-ICD-Loader\RelWithDebInfo\OpenCL.lib
Microsoft (R) COFF/PE Dumper Version 14.29.30143.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file external\OpenCL-ICD-Loader\RelWithDebInfo\OpenCL.lib

File Type: LIBRARY

     Exports

       ordinal    name

                  _clBuildProgram@24
                  _clCloneKernel@8
                  _clCompileProgram@36
...
```

2. The actual OpenCL.dll I built has both decorated and undecorated functions when I build RelWithDebInfo:

```cmd
>dumpbin /exports external\OpenCL-ICD-Loader\RelWithDebInfo\OpenCL.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30143.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file external\OpenCL-ICD-Loader\RelWithDebInfo\OpenCL.dll

File Type: DLL

  Section contains the following exports for OpenCL.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
         123 number of functions
         123 number of names

    ordinal hint RVA      name

          1    0 0000139D clBuildProgram = @ILT+920(_clBuildProgram@24)
          2    1 00001393 clCloneKernel = @ILT+910(_clCloneKernel@8)
          3    2 00001505 clCompileProgram = @ILT+1280(_clCompileProgram@36)
...
```

3. If I build a Release OpenCL.dll, though, I do NOT have decorated functions.  This also matches the DLL I have in my `c:\windows\syswow64` from a desktop GPU driver package:

```cmd
c:\Windows\SysWOW64>dumpbin /exports OpenCL.dll
Microsoft (R) COFF/PE Dumper Version 14.29.30143.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file OpenCL.dll

File Type: DLL

  Section contains the following exports for OpenCL.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
         123 number of functions
         123 number of names

    ordinal hint RVA      name

          1    0 00001B80 clBuildProgram
          2    1 00004020 clCloneKernel
          3    2 00001BA0 clCompileProgram
...
```

Not sure how the import lib is getting the decorated functions when the functions are undecorated in OpenCL.def but perhaps that's the reason the MSVC builds are working?

**Comment by jenatali** [comment]
While not an expert at MinGW, someone recently contributed some patches to Mesa to generate .def files that seem to work for MinGW: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/bin/gen_vs_module_defs.py. Specifically, they use the format of `function@8 == function` instead of `function = function@8`. Perhaps that might help?

**Comment by bashbaug** [comment]
> Perhaps that might help?

Thanks, I'll give this a look!

**Comment by bashbaug** [comment]
:tada: The `function@8 == function` syntax worked perfectly and I'm able to build an OpenCL.dll with mingw-i686 that works now.  Thanks a ton! :tada:

**Comment by lb90** [comment]
Hello! This is was actually a binutils issue, see: https://sourceware.org/bugzilla/show_bug.cgi?id=30421. A fix has been committed and will be present in the upcoming binutils 2.41 release (due in August)
