### ISSUE TITLE
Sigverif.exe says opencl.dll is not signed

### ISSUE THREAD

**Issue by ValZapod** [KhronosGroup/OpenCL-ICD-Loader#194]
This is to Intel people. So OpenCL.dll ICD loader 3.0.2.0 is part of Windows 11 22H2, right, in two places, under System32 and SysWOW64. And sigverif.exe says it does not like the Intel signature.

See for example https://social.technet.microsoft.com/Forums/windows/en-US/d7e93877-2f0f-4b86-a5d6-e903644fce0d/recurrent-test-mode-due-to-opencldll-not-signed-?forum=win10itprogeneral

That is very bad, since it breakes Secure Boot perfection.

**Comment by bashbaug** [comment]
I've reached out to our installer team.

Can you please confirm:
* This is for OpenCL.dll, not OpenCL.exe?
* Which driver version are you using?

Thanks!

**Comment by ValZapod** [comment]
Opencl.dll indeed.

Driver? It is part of windows, I think.

Can yu confirm the issue when running sigveriexe?

**Comment by ValZapod** [comment]
Opencl.dll is now signed in version 3.0.3.0 and is shown as part of nv_disp.cat, i.e. nvidia driver.
