### ISSUE TITLE
icd_exports path

### ISSUE THREAD

**Issue by petrkalos** [KhronosGroup/OpenCL-ICD-Loader#2]
When ICD-Loader is being used as subproject, CMAKE_SOURCE_DIR in CMakeLists.txt:25 is not producing the correct path to icd_exports.map.
I think that PROJECT_SOURCE_DIR is more suitable.

**Comment by kepatil** [comment]
I think this makes sense. I will try the suggestion locally and incorporate it.

**Comment by kepatil** [comment]
Fixed with c262c83.
