### ISSUE TITLE
new CI failure related to Ubuntu gcc-11

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-ICD-Loader#200]
We seem to have a new CI failure now, due to gcc-11 on Ubuntu.  Example:

https://github.com/KhronosGroup/OpenCL-ICD-Loader/actions/runs/3463417895/jobs/5784936379#step:4:85

```
Cannot add PPA: 'ppa:~ubuntu-toolchain-r/ubuntu/test'.
ERROR: '~ubuntu-toolchain-r' user or team does not exist.
```

Here is the related CI section, showing that this is gcc-11 specific:

```
    - name: Create Build Environment
      run: sudo apt-get update -q;
        if [[ "${{matrix.GEN}}" =~ "Ninja" && ! `which ninja` ]]; then sudo apt install -y ninja-build; fi;
        if [[ "${{matrix.COMPILER}}" =~ "gcc-11" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi;
```

I'll try to get this working again, otherwise we can disable gcc-11 testing temporarily.

**Comment by Kerilk** [comment]
@bashbaug I reran the failed test, they passed. This is a network issue, where sometimes either the PPA or the key server fail to answer.

**Comment by bashbaug** [comment]
Ok phew, I tried re-running them several times but they failed consistently.  Glad to hear they're passing now though!  I'll close this issue.
