### ISSUE TITLE
OpenCL installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by hnakahara79** [KhronosGroup/OpenCL-ICD-Loader#220]
Dear Developers,

I am new to openCL and would like to install it on Ubuntu 20.04 LTS. ( I am not sure if this is the correct place to ask, but I am trying to see if someone can guide me ). 

I followed the steps documented in the following link:

( https://github.com/KhronosGroup/OpenCL-Guide/blob/main/chapters/getting_started_linux.md )

The steps I followed are:

sudo apt update
sudo apt upgrade
sudo apt install build-essential -y
sudo apt install git -y
sudo apt install cmake -y
sudo snap install --classic code
sudo apt install opencl-headers ocl-icd-opencl-dev -y

After that I got confused (about where to stop) because next it shows instructions with the caption "Compiling on the command-line"

My question is: Should I continue to follow or installation of OpenCL is done with the commands I used ?

Any help or suggestion would be greatly appreciated.

Thanks a lot.

**Comment by Kerilk** [comment]
Hello,
When you executed:
`sudo apt install opencl-headers ocl-icd-opencl-dev -y`
You installed the OpenCL headers and the OpenCL driver loader. This is enough to create OpenCL applications.

Should you want to run an OpenCL application you would need an OpenCL driver. A CPU implementation like POCL should be easy enough:
`sudo apt-get install -y pocl-opencl-icd`
You can test you installation by installing `clinfo`:
`sudo apt-get install -y clinfo`
And running it:
`clinfo`
Which should list POCL as an available driver.

**Comment by hnakahara79** [comment]
Dear @Kerilk 

Thank you very much for quick reply. I followed your suggestions and looks like things are fine. 

I am very grateful to you. 

Thank you so so much.

**Comment by arun-mani-j** [comment]
Hii. I faced the same and had it fixed via help from https://github.com/KhronosGroup/OpenCL-Docs/discussions/1158.

Can we add the instruction about `pocl` to https://github.com/KhronosGroup/OpenCL-Guide/blob/main/chapters/getting_started_linux.md?
