### ISSUE TITLE
Branches per version

### ISSUE THREAD

**Issue by VincentSC** [KhronosGroup/OpenCL-ICD-Loader#3]
It would be nice to have a branch per OpenCL version

**Comment by kepatil** [comment]
Hi Vincent, can you elaborate on the need for branches? The ICD loader is backward compatible by design so using the latest ICD loader would work for all OpenCL versions.

**Comment by VincentSC** [comment]
Thank you - I needed to know that. Could you please add this info to the readme?

What about the deprecated functions, which will be removed in a later version?

**Comment by kepatil** [comment]
ICD loader will not remove deprecated functions so applications will link correctly and calls to such functions will be routed as usual to the underlying vendor platform(s). After that it is up to the platform to support deprecated functionality.

Adding a note in the README makes sense.

**Comment by VincentSC** [comment]
Thanks Kedar! Great info to know!
