### ISSUE TITLE
Support for environment variable OCL_ICD_VENDORS

### ISSUE THREAD

**Issue by noma** [KhronosGroup/OpenCL-ICD-Loader#31]
Please add support for non-standard ICD directory via the `OCL_ICD_VENDORS` environment variable already supported by some loaders. Here is a patch from the PoCL project:

https://github.com/pocl/pocl/blob/master/tools/patches/khronos-icd-loader.patch

**Comment by kepatil** [comment]
The OpenCL working group has carefully considered this in the past and decided not to do it. Please see [my comment on issue #4](https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/4#issuecomment-244351420).
