### ISSUE TITLE
build error: CL_API_SUFFIX__VERSION_2_2 in icd_dispatch.h

### ISSUE THREAD

**Issue by pint1022** [KhronosGroup/OpenCL-ICD-Loader#34]
Hello,
I just checkout repo, and use 'make' to build. It reports the following error:
...
OpenCL-ICD-Loader/icd_dispatch.h:329:38: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CL_API_SUFFIX__VERSION_2_2’
     const void*          spec_value) CL_API_SUFFIX__VERSION_2_2;

...

can someone shed some lights on this solution?

thanks,

**Comment by sarahM0** [comment]
Hi,
I have the same issue. I'm on a linux machine and I'm using https://github.com/KhronosGroup/OpenCL-Headers which is suppose to work with all openCL versions so I don't know what did @pint1022 change. Any ideas?

**Comment by pint1022** [comment]
@sarahM0 you might have the mis-matching version between 'ICD_Loader' source code to build and OpenCL lib installed on the system.

**Comment by sarahM0** [comment]
Thanks @pin1022!
