### ISSUE TITLE
how to read the traces from KHR_ICD_TRACE calls?

### ISSUE THREAD

**Issue by pint1022** [KhronosGroup/OpenCL-ICD-Loader#36]
Hello
is there a guide of how to read traces?

thanks,
steven

**Comment by kepatil** [comment]
I do not understand your problem. Can you explain what you are trying to do?

**Comment by pint1022** [comment]
Just want to find out how to get the logs from ICD_loader run. The source codes have a lot of calls to the function: 'KHR_ICD_TRACE'. where does it dump the messages?


best
steven

**Comment by kepatil** [comment]
Hi @pint1022, apologies for the late response to your comment above. I did not notice that you had replied. :-(

The trace calls print to stderr. You can try turning them on at https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/master/icd.h#L144.

A fair warning though: The trace calls were put only for debugging the ICD loader and are not for production use. So they are not as regularly exercised as the rest of the code. So YMMV, but I'll gladly accept patches to fix any issues you see in the traces.
