### ISSUE TITLE
Appveyor Continuous Integration 

### ISSUE THREAD

**Issue by mancoast** [KhronosGroup/OpenCL-ICD-Loader#41]
Greetings,

Please enable cloud compilation for repeatable build steps.

Thanks!
coast

**Comment by bashbaug** [comment]
I created PR #63 to add Appveyor CI.

**Comment by bashbaug** [comment]
AppVeyor CI was added via commit 25e7faa6de5da4edeed48e4d8763730f29fdd3ef and is enabled for this repo, so I am closing this issue.  Thanks!

**Comment by mancoast** [comment]
Thanks!
