### ISSUE TITLE
Environment Variable Support

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-ICD-Loader#48]
There have been a few issues requesting support for various OpenCL ICD loader environment variables.  For example:

* https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/31
* https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/4

We've seen similar requests on the Intel OpenCL forums, such as:

* https://software.intel.com/en-us/forums/opencl/topic/802064

I know these issues have been closed in the past as "won't fix", but I believe we should reconsider this decision.  Note that the Vulkan loader provides support for various environment variables:

* https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#table-of-debug-environment-variables

I'd like to see OpenCL ICD loader environment variable support at least for loading ICDs from a location other than `/etc/OpenCL/vendors`, and for controlling debug output to help root-cause installation problems.  Are there best practices from the Vulkan loader that we could apply to add similar functionality to the OpenCL ICD loader?

**Comment by bensallen** [comment]
I agree with @bashbaug in this request. Hard coding the location to /etc/OpenCL/vendors makes alternative path installs difficult, eg. installing to a shared filesystem.

Currently we are hex-editing the loader in Intel's OpenCL SDK to make the install suitable for our environment. This obviously is not particularly ideal.

**Comment by mmha** [comment]
Here's another use case: I intend to submit [the headers](https://github.com/mmha/conan-opencl-headers), [the ICD](https://github.com/mmha/conan-opencl-icd-loader) and cl.hpp (WIP) to [Bincrafters](https://github.com/bincrafters/) for inclusion in their [Conan repository](https://bintray.com/bincrafters/public-conan/).

Having environment variable support is *essential* for the ICD loader to find OpenCL implementations that may be installed as a Conan package at a non-standard location.

This is most likely also required for all the Linux distributions that don't follow the FHS like Clear Linux, Nix and Guix.

**Comment by bashbaug** [comment]
PR #77 was just merged, so this ICD loader now supports environment variables to enumerate ICDs from a location other than `/etc/OpenCL/vendors`.  Please see the [README](https://github.com/KhronosGroup/OpenCL-ICD-Loader#table-of-debug-environment-variables) for details.

I'd still like to add support for controlling debug output via environment variables but this has lower priority, I think.

We're also reviewing PR #45, which adds support for filtering devices using environment variables.

**Comment by bashbaug** [comment]
We have a bunch of documented environment variables now so I think we can close this issue and add new issues to track any new requests.  Thanks!
