### ISSUE TITLE
Skip tests on build

### ISSUE THREAD

**Issue by Brainiarc7** [KhronosGroup/OpenCL-ICD-Loader#5]
Hello,

Is it possible to skip all tests on build?
Is there a Cmake configuration option that can disable the generation of all test(s)?

**Comment by jrprice** [comment]
Maybe I didn't quite understand what you're asking, but if you just want to build the ICD loader library, then you can use the `OpenCL` target:
    
    # e.g. with GNU Make
    make OpenCL

This will not build any of the tests.

**Comment by Brainiarc7** [comment]
Ah, I see, thanks :-)

**Comment by Brainiarc7** [comment]
And after running the make OpenCL (to build the OpenCL target), would running make install install the library?

**Comment by jrprice** [comment]
We don't provide an `install` target at present - the library is just built in a `bin/`directory.

**Comment by Brainiarc7** [comment]
Alright, thanks for the clarification.

**Comment by kepatil** [comment]
Closing issue as I see no open questions.
