### ISSUE TITLE
Need ProductVersion string?

### ISSUE THREAD

**Issue by b-sumner** [KhronosGroup/OpenCL-ICD-Loader#52]
In the StringInfoFile Block in OpenCL.rc, there is a FileVersion string but no ProductVersion.  Should there be a ProductVersion string?  Some releases want to control the FileVersion, but leave the ProductVersion alone.

**Comment by kepatil** [comment]
I am not sure. Are there any cons if we add ProductVersion? Will the ICD installation guidelines need an update too?
