### ISSUE TITLE
icd_loader_test test fails

### ISSUE THREAD

**Issue by trecakov** [KhronosGroup/OpenCL-ICD-Loader#54]
make -C build test
make[1]: Entering directory `/software/packages/OpenCL-ICD-Loader/build'
Running tests...
Test project /software/packages/OpenCL-ICD-Loader/build
    Start 1: OPENCL_ICD_LOADER_TEST
1/1 Test #1: OPENCL_ICD_LOADER_TEST ...........***Failed    0.11 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.12 sec

The following tests FAILED:
	  1 - OPENCL_ICD_LOADER_TEST (Failed)
Errors while running CTest
make[1]: *** [test] Error 8
make[1]: Leaving directory `/software/packages/OpenCL-ICD-Loader/build'
make: *** [test] Error 2

Running test directly gives:
ERROR: App log and stub log differ.
ICD Loader Test FAILED

Any suggestions? Using OpenCL 2.2

**Comment by bashbaug** [comment]
I think I debugged and fixed this a while back.  I've been meaning to clean up my changes and create several PRs since I have a bunch of changes combined together right now.

Can you try this small change to the clCreateImage2D test?  I believe it fixed the failure.

https://github.com/bashbaug/OpenCL-ICD-Loader/commit/6c1699eab7ea7b61b26aa8d5cd8c6f9d1f5cf7d4#diff-91d41ad6f2fc7984516f35fda9b0fd1bR481

**Comment by trecakov** [comment]
I tried it, but it doesnt seem that fixes it. Any other suggestions?

**Comment by bashbaug** [comment]
Ah, great, the fix I sent previously was committed in https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/21aa894095a3d3ac7bb5c6ddb421382019969d62, so it's not needed anymore.

That does mean that I'm not sure what's causing your issue though, unfortunately.  Since it says that the "app log" and "stub log" differ could you try diff'ing the two to see what the difference is?

The two files are `icd_test_app_log.txt` and `icd_test_stub_log.txt`, and should be in your `test` directory.

**Comment by trecakov** [comment]
The output is:

1,200d0
< clGetDeviceIDs((nil), 0, 1, 0x60eab8, (nil))
< Value returned: -32
< clCreateContext((nil), 1, 0x60eab8, 0x40839d, (nil), (nil))
< Value returned: (nil)
< clReleaseContext((nil))
< Value returned: -34
< clCreateContextFromType(0x60e3e0, 0, 0x40839d, (nil), (nil))
< Value returned: (nil)
< clCreateCommandQueue((nil), (nil), 0, (nil))
< Value returned: (nil)
< clCreateBuffer((nil), 0, 0, (nil), (nil))
< Value returned: (nil)
< clCreateSubBuffer((nil), 0, 0, (nil), (nil))
< Value returned: (nil)
< clCreateImage((nil), 0, (nil), (nil), (nil), (nil))
< Value returned: (nil)
< clReleaseMemObject((nil))
< Value returned: -38
< clCreateImage2D((nil), 0, (nil), 0, 0, 0, (nil), (nil))
< Value returned: (nil)
< clReleaseMemObject((nil))
< Value returned: -38
< clCreateImage3D((nil), 0, (nil), 0, 0, 0, 0, 0, (nil), (nil))
< Value returned: (nil)
< clCreateSampler((nil), 0, 0, 0, (nil))
< Value returned: (nil)
< clCreateProgramWithSource((nil), 0, (nil), (nil), (nil))
< Value returned: (nil)
< clReleaseProgram((nil))
< Value returned: -44
< clCreateProgramWithBinary((nil), 0, 0x60eab8, (nil), (nil), (nil), (nil))
< Value returned: (nil)
< clReleaseProgram((nil))
< Value returned: -44
< clCreateProgramWithBuiltInKernels((nil), 0, 0x60eab8, (nil), (nil))
< Value returned: (nil)
< clCreateKernel((nil), (nil), (nil))
< Value returned: (nil)
< clCreateKernelsInProgram((nil), 0, 0x60eac8, (nil))
< Value returned: -44
< clCreateUserEvent((nil), (nil))
< Value returned: (nil)
< clRetainContext((nil))
< Value returned: -34
< clGetContextInfo((nil), 0, 0, (nil), (nil))
< Value returned: -34
< clGetDeviceInfo((nil), 0, 0, (nil), (nil))
< Value returned: -33
< clCreateSubDevices((nil), (nil), 0, 0x60eab8, (nil))
< Value returned: -33
< clRetainDevice((nil))
< Value returned: -33
< clRetainCommandQueue((nil))
< Value returned: -36
< clGetCommandQueueInfo((nil), 0, 0, (nil), (nil))
< Value returned: -36
< clRetainKernel((nil))
< Value returned: -48
< clSetKernelArg((nil), 0, 0, (nil))
< Value returned: -48
< clGetKernelInfo((nil), 0, 0, (nil), (nil))
< Value returned: -48
< clGetKernelArgInfo((nil), 0, 0, 0, (nil), (nil))
< Value returned: -48
< clGetKernelWorkGroupInfo((nil), (nil), 0, 0, (nil), (nil))
< Value returned: -48
< clEnqueueMigrateMemObjects((nil), 0, (nil), 0, 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueNDRangeKernel((nil), (nil), 0, (nil), (nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueTask((nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueNativeKernel((nil), (nil), (nil), 0, 0, (nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clSetUserEventStatus((nil), 0)
< Value returned: -58
< clWaitForEvents(1, 0x60eab0)
< Value returned: -58
< clGetEventInfo((nil), 0, 0, (nil), (nil))
< Value returned: -58
< clSetEventCallback((nil), 0, 0x408434, (nil))
< Value returned: -58
< clRetainEvent((nil))
< Value returned: -58
< clEnqueueMarker((nil), 0x60eab0)
< Value returned: -36
< clEnqueueBarrier((nil))
< Value returned: -36
< clEnqueueMarkerWithWaitList((nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueBarrierWithWaitList((nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clGetEventProfilingInfo((nil), 0, 0, (nil), (nil))
< Value returned: -58
< clFlush((nil))
< Value returned: -36
< clFinish((nil))
< Value returned: -36
< clEnqueueReadBuffer((nil), (nil), 0, 0, 0, (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueWriteBuffer((nil), (nil), 0, 0, 0, (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueReadBufferRect((nil), (nil), 0, (nil), (nil), (nil), 0, 0, 0, 0, (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueWriteBufferRect((nil), (nil), 0, (nil), (nil), (nil), 0, 0, 0, 0, (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueFillBuffer((nil), (nil), (nil), 0, 0, 0, 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueCopyBuffer((nil), (nil), (nil), 0, 0, 0, 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueCopyBufferRect((nil), (nil), (nil), (nil), (nil), (nil), 0, 0, 0, 0, 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueMapBuffer((nil), (nil), 0, 0, 0, 0, 0, (nil), 0x60eab0, (nil))
< Value returned: (nil)
< clRetainMemObject((nil))
< Value returned: -38
< clSetMemObjectDestructorCallback((nil), 0x4083dc, (nil))
< Value returned: -38
< clEnqueueUnmapMemObject((nil), (nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clGetMemObjectInfo((nil), 0, 0, (nil), (nil))
< Value returned: -38
< clRetainProgram((nil))
< Value returned: -44
< clBuildProgram((nil), 0, 0x60eab8, (nil), 0x408408, (nil))
< Value returned: -44
< clCompileProgram((nil), 0, 0x60eab8, (nil), 0, (nil), 0x408408, (nil))
< Value returned: -44
< clLinkProgram((nil), 0, (nil), (nil), 0, (nil), 0x408408, (nil), (nil))
< Value returned: (nil)
< clGetExtensionFunctionAddressForPlatform((nil), 0x40af30)
< Value returned: (nil)
< clUnloadPlatformCompiler((nil))
< Value returned: -32
< clGetProgramInfo((nil), 0, 0, (nil), (nil))
< Value returned: -44
< clGetProgramBuildInfo((nil), (nil), 0, 0, (nil), (nil))
< Value returned: -44
< clGetSupportedImageFormats((nil), 0, 0, 0, (nil), (nil))
< Value returned: -34
< clEnqueueCopyImageToBuffer((nil), (nil), (nil), (nil), (nil), 0, 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueCopyBufferToImage((nil), (nil), (nil), 0, (nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueMapImage((nil), (nil), 0, 0, (nil), (nil), (nil), (nil), 0, (nil), 0x60eab0, (nil))
< Value returned: (nil)
< clEnqueueReadImage((nil), (nil), 0, (nil), (nil), 0, 0, (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueWriteImage((nil), (nil), 0, (nil), (nil), 0, 0, (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueFillImage((nil), (nil), (nil), (nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clEnqueueCopyImage((nil), (nil), (nil), (nil), (nil), (nil), 0, (nil), 0x60eab0)
< Value returned: -36
< clGetImageInfo((nil), 0, 0, (nil), (nil))
< Value returned: -38
< clRetainSampler((nil))
< Value returned: -41
< clGetSamplerInfo((nil), 0, 0, (nil), (nil))
< Value returned: -41
< clCreateFromGLBuffer((nil), 0, 0, (nil))
< Value returned: (nil)
< clCreateFromGLTexture((nil), 0, 0, 0, 0, (nil))
< Value returned: (nil)
< clCreateFromGLTexture2D((nil), 0, 0, 0, 0, (nil))
< Value returned: (nil)
< clCreateFromGLTexture3D((nil), 0, 0, 0, 0, (nil))
< Value returned: (nil)
< clCreateFromGLRenderbuffer((nil), 0, 0, (nil))
< Value returned: (nil)
< clGetGLObjectInfo((nil), (nil), (nil))
< Value returned: 0xffffffda
< clGetGLTextureInfo((nil), 0, 0, (nil), (nil))
< Value returned: 0xffffffda
< clEnqueueAcquireGLObjects((nil), 0, (nil), 0, 0x60eab0, 0x60eab0)
< Value returned: 0xffffffdc
< clEnqueueReleaseGLObjects((nil), 0, (nil), 0, 0x60eab0, 0x60eab0)
< Value returned: 0xffffffdc
< clCreateEventFromGLsyncKHR((nil), (nil), (nil))
< Value returned: (nil)
< clGetGLContextInfoKHR(0x60e3e0, 0, 0, (nil), (nil))
< Value returned: 0xffffffe0
< clReleaseSampler((nil))
< Value returned: -41
< clReleaseMemObject((nil))
< Value returned: -38
< clReleaseMemObject((nil))
< Value returned: -38
< clReleaseEvent((nil))
< Value returned: -58
< clReleaseKernel((nil))
< Value returned: -48
< clReleaseProgram((nil))
< Value returned: -44
< clReleaseCommandQueue((nil))
< Value returned: -36
< clReleaseContext((nil))
< Value returned: -34
< clReleaseDevice((nil))
< Value returned: -33

**Comment by bashbaug** [comment]
> The output is:
> ...

If this is the only output you are seeing then it looks like one of the files is empty.

Have you added the tester stub as an ICD as described in the README?

We really need to find a way to do testing without requiring modifications to /etc...

**Comment by trecakov** [comment]
Yes, icd_test_stub_log.txt is empty.
Yes, I had added tester stub as an ICD, but I did not place it in /etc/ directory because I did not want to put anything there. I just tested id, and it worked. 

Thanks for the help! @bashbaug
