### ISSUE TITLE
OpenCL-ICD-Loader for version 1.1

### ISSUE THREAD

**Issue by Mezzano** [KhronosGroup/OpenCL-ICD-Loader#7]
Hello,

we're trying to activate and use GPU vivante gc200 on imx6q board ARM 7 with linux 3.10.31 and distribution opensuse 13.1.

The GPU is opencl 1.1 EP enabled and we are looking for an libOpenCL.so.
OpenCL-ICD-Loader doesn't seem to support OpenCL 1.1., where can we find such a library?

**Comment by kepatil** [comment]
OpenCL ICD Loader is backwards compatible by design so it should work with all versions of OpenCL till date. If you are seeing unexpected behavior while using it then please file a separate issue and provide details.

**Comment by ptomulik** [comment]
Hi, I'd like to join to this question. I have a project of C++ library which uses OpenCL. As a part of build it downloads ICD loader, builds it up and uses as its own library. To this end I was able to build and test my project against several versions of OpenCL/ICD loader (1.0, 1.1, ..). Now it looks like I'm restricted to only 2.1 ICD loader. Is there a place where I could still download older versions of the ICD loader (source code)? Will you provide tags/versions for this github repo in future?
