### ISSUE TITLE
Move the dispatch table declaration to OpenCL-Headers?

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-ICD-Loader#72]
The various function pointer types as well as the declaration for the dispatch table in `icd_dispatch.h` would be easier to reuse directly in OpenCL implementations if they were part of OpenCL-Headers.

It seems to me that only the declaration for the structure types at the bottom of the file should be part of the ICD loader itself.

Is there a good reason to not do that?

**Comment by bashbaug** [comment]
Interesting idea.  This makes sense to me.  I think it could be useful for some other projects as well, and not just for OpenCL implementations.

At some point I'd also like to investigate generating things like the function pointer types automatically from the API cl.xml file.

**Comment by mmha** [comment]
A while ago I wrote a small clang tool for a similar use case. It takes a header with (member) function declarations generates a cpp file with a table of function pointers that are either eagerly initialized after loading the shared object (emulating the PLT, so no runtime overhead) or lazily through static variables ([example output](https://gist.github.com/mmha/ba4fa54affbd79a1236bcd4d8daf126a)). It's basically an ICD loader generator for arbitrary APIs.

I can clean up the source, make it suitable for the ICD and make it public if that's of any interest.

The headers should contain the declarations in my opinion, nothing else. I would prefer it to generate the tables as part of the ICD loader build, be it from cl.xml (probably saner) or a clang tool accepting the headers.

**Comment by kpet** [comment]
@bashbaug Thanks for the feedback. I'll create PRs when I find a bit of time to spend on this. Agree a lot of this can be generated.

@mmha That sounds cool but I'm wondering whether that's not a bit overkill for what we're doing here, especially given that we have a description of the API in machine-parseable form. Also, generating the tables comes with the interesting issue of guaranteeing that the order of members remain the same as that of the current structure. I think we have far too much code in the wild that relies on this order to change it now.
