### ISSUE TITLE
AMD opencl uses REG_MULTI_SZ  for OpenCLDriverName

### ISSUE THREAD

**Issue by dooglz** [KhronosGroup/OpenCL-ICD-Loader#84]
I Have a windows system with both Nvidia and AMD gpus, both individual vendor opencl driver work when used directly. Using this ICD the amd driver fails to be detected because AMD have used 
**REG_MULTI_SZ** rather than **REG_SZ** for the OpenCLDriverName.

I know this is technically AMD's fault as they are going against the docs here
https://github.com/KhronosGroup/OpenCL-Docs/blob/master/ext/cl_khr_icd.txt#L71

If the maintainers want to allow this small deviation from the spec: See pull request for quick fix. #85

**Comment by saleelk** [comment]
The issue has been fixed in AMD trunk and new drivers should ship with REG_SZ

**Comment by b-sumner** [comment]
This can be closed since it is no longer necessary.

**Comment by bashbaug** [comment]
Closing as per the [comment above](https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/84#issuecomment-520896371).
